# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Python Package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # Install build deps
        python3 -m pip install setuptools wheel twine flake8 pytest

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        # Install the package from setup.py
        python3 setup.py install

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide

    - name: Test with pytest
      run: |
        cd vdocipher/tests
        pytest
        cd ../..
      env:
        VDOCIPHER_API_SECRET: ${{ secrets.VDOCIPHER_API_SECRET }}

     # Upload to TestPyPI
    - name: Build and Upload to TestPyPI
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PUZZL_PROD }}
